### PR TITLE
Added an Either type Decoder.

### PR DESCRIPTION
**Pull request by MichaelCombs28**
Just a convenience function since I tend to use this library a lot to distinguish it from Result.

### CODE REVIEW

**Comment by toastal** [comment]
I really dislike the name. `Either.either` will confuse Haskellers as https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Either.html#v:either or `unpack` in this library. Community seems to be against that style of naming too. Perhaps `Either.decodeEither` or just `Either.decode`?

**Comment by MichaelCombs28** [comment]
My original name was decodeEIther, but in Elm decode means to literally decode, take for instance decodeString. In the Json.Decode library most things are named literally such as list, string, int, etc.

Coming from Haskell myself I understand that conventions are different (take applicative functions being called map2 map3 etc.)

Ultimately it's your library, if you decide I change the name I'll do it.

**Comment by toastal** [comment]
I had the same knee-jerk with `decodeString` in mind, but I almost feel like `decodeBoth` might be the ticket. It's like `mapBoth`, but says what kind of transformation (Either to Decoder) it's going to be. Or like `bothToDecoder`??

**Comment by MichaelCombs28** [comment]
This got confusing lol, how about eitherDecoder? 

If we want to mapBoth over the decoder itself we could always just create an Either.Json.Decode module or something. That seems to be the standard for Elm. 

Say Either.Json.Decode.mapBoth as a new Either Decoding pipeline or something which would be nice.

If you like the idea I can bang it out within the hour.

**Comment by toastal** [comment]
Ah, yeah that's alright.

**Comment by MichaelCombs28** [comment]
Well I remembered to get back to this, sorry about forgetting, but I ended up doing unnecessary stuff like lifting all the Either module functions, then I realized, all we ever really needed here was just the either decoder within a module that makes sense.

The lack of type classes is pretty painful. Hopefully when web assembly is ready we'll be able to use an efficient browser-side Haskell.

I didn't add it to exposed modules, so you can commit it, tag it, then bump it.

**Pull request merged**
